const Event = {
    PIXEL: {
        NEW_PIXEL_ADDED: 'NEW_PIXEL_ADDED',
        NEW_PIXEL_REMOVED: 'NEW_PIXEL_REMOVED',
        PIXELS_IS_PERSISTED: 'PIXELS_IS_PERSISTED',
        NO_PERSISTED_PIXELS: 'NO_PERSISTED_PIXELS',
        CONNECTED_USERS_CHANGED: 'CONNECTED_USERS_CHANGED',
    },
    GENERAL: {
        INFO: 'INFO',
        ERROR: 'ERROR',
        CONNECTION_SUCCESS: 'CONNECTION_SUCCESS',
    }
}

export default Event;